name: Update Change Log
on:
  - push
jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'auto(CHANGELOG): update `CHANGELOG.md` file'
          commit_options: '--no-verify --signoff'
          file_pattern: 'CHANGELOG.md'
          commit_user_name: Git Cliff
